//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goji.TestApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Goji.TestApp.Resources.MainWindow", typeof(MainWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bound 1.
        /// </summary>
        internal static string _aBindingTranslatedValue1 {
            get {
                return ResourceManager.GetString("_aBindingTranslatedValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bound 2.
        /// </summary>
        internal static string _aBindingTranslatedValue2 {
            get {
                return ResourceManager.GetString("_aBindingTranslatedValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dynamic.
        /// </summary>
        internal static string _aDynamicTranslatedValue {
            get {
                return ResourceManager.GetString("_aDynamicTranslatedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A numeric value.
        /// </summary>
        internal static string _aNumericValue {
            get {
                return ResourceManager.GetString("_aNumericValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to static.
        /// </summary>
        internal static string _aStaticTranslatedValue {
            get {
                return ResourceManager.GetString("_aStaticTranslatedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics.
        /// </summary>
        internal static string _basicsItemTabHeader {
            get {
                return ResourceManager.GetString("_basicsItemTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding Translation Extension.
        /// </summary>
        internal static string _bindingTranslationExtension {
            get {
                return ResourceManager.GetString("_bindingTranslationExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force GC.
        /// </summary>
        internal static string _cg {
            get {
                return ResourceManager.GetString("_cg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current time.
        /// </summary>
        internal static string _currentTime {
            get {
                return ResourceManager.GetString("_currentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Translation Extension.
        /// </summary>
        internal static string _dynamicTranslationExtension {
            get {
                return ResourceManager.GetString("_dynamicTranslationExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element count.
        /// </summary>
        internal static string _elementCount {
            get {
                return ResourceManager.GetString("_elementCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback test.
        /// </summary>
        internal static string _fallbackValue {
            get {
                return ResourceManager.GetString("_fallbackValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric values and dates are always in the right format..
        /// </summary>
        internal static string _formattingDesc {
            get {
                return ResourceManager.GetString("_formattingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate list new.
        /// </summary>
        internal static string _genListElements {
            get {
                return ResourceManager.GetString("_genListElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goji-Test Application.
        /// </summary>
        internal static string _mainWindowTitle {
            get {
                return ResourceManager.GetString("_mainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Leak Test.
        /// </summary>
        internal static string _memLeakTest {
            get {
                return ResourceManager.GetString("_memLeakTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to english element.
        /// </summary>
        internal static string _memTestElementValue {
            get {
                return ResourceManager.GetString("_memTestElementValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Translation Extension.
        /// </summary>
        internal static string _staticTranslationExtension {
            get {
                return ResourceManager.GetString("_staticTranslationExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
    }
}
